# Generated by Django 3.2.13 on 2023-06-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educaGamez', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='opcaoA',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='opcaoB',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='opcaoC',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='opcaoD',
            new_name='D',
        ),
    ]
