# Generated by Django 3.2.13 on 2023-06-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educaGamez', '0002_auto_20230606_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=300)),
                ('n_resp_certa', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='A',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='B',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='C',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='D',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='conteudo',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='resposta',
            name='certa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resposta',
            name='conteudo',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educaGamez.pergunta'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educaGamez.categoria'),
        ),
    ]
