# Generated by Django 3.2.13 on 2023-06-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educaGamez', '0004_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('escola', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=100)),
                ('soma', models.CharField(max_length=100)),
                ('subtração', models.CharField(max_length=100)),
                ('multiplicação', models.CharField(max_length=100)),
                ('divisão', models.CharField(max_length=100)),
                ('geral', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
