# Generated by Django 3.2.13 on 2023-06-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educaGamez', '0005_auto_20230630_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
