# Generated by Django 3.2.13 on 2023-07-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educaGamez', '0007_auto_20230704_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
